### ISSUE TITLE
merge devel and kinetic

### ISSUE THREAD

**Issue by minhnh** [b-it-bots/mas_perception#29]
Apparently, there has been quite a bit of divergence between `kinetic` and `devel`. We need to sit down and resolve all the conflicts at one point.

Related issues: #4, #5

**Comment by mhwasil** [comment]
I do not know the state in the devel currently since we, @work team at least, never work using devel. But yes, sure, we can sit and resolve the issues.

**Comment by minhnh** [comment]
@mhwasil it makes no sense to have one repository and two separated code base. May as well make it into 2 repositories then. @argenos @sthoduka I believe we need to discuss how this repo is managed if somehow this is an accepted mindset.

**Comment by argenos** [comment]
All pull requests should be to `devel`, never to `kinetic`. @mhwasil can you open a pull request to include all the changes in `kinetic` to `devel` and fix the resulting conflicts?

**Comment by minhnh** [comment]
For future reference, please refer to [b-it-bots convention wiki](https://b-it-bots.github.io/wiki/conventions/), particularly the [git branching model guideline](https://b-it-bots.github.io/wiki/conventions/git/branching-model/), to learn more about the branching workflow.

@argenos It seems this page hasn't been maintained in a while and not well communicated? Maybe we can link to it in the main repositories' `README` files?
