### ISSUE TITLE
create package to generate labeled data from the green box

### ISSUE THREAD

**Issue by minhnh** [b-it-bots/mas_perception#31]
Ideally labeled data should be both segmentation and bounding boxes, for both point clouds and images. Background subtraction algorithms may be more aligned with segmentation, however, and a first working version for images is fine.

relevant links:
* https://mathematica.stackexchange.com/questions/132844/nontrivial-background-removal
* https://docs.opencv.org/3.4/d7/d1c/tutorial_js_watershed.html
* software which has built-in background subtraction: https://www.blender.org/
* [tutorial with utility functions that may be of use](https://github.com/b-it-bots/mas_tutorials/blob/master/domestic_robotics/perception.ipynb)

**Comment by minhnh** [comment]
Please keep @henrikschnor and @robertocaiwu in the loop so they can contribute as needed. Since @PatrickNa is the creator of the box, please ask him about issues related to physical modifications and design.

**Comment by PatrickNa** [comment]
I additionally assigned @ErickKramer since he wanted to take care of the learning.

**Comment by njanirudh** [comment]
I am working on precise object segmentation in the green box.
While working on a small dataset of  images taken in the box I saw a few problems :

1. The lights are bright and are causing a white blob near the source. 
I think this problem can be mitigated using **diffusion papers** on the light sources.
It will also improve the object image quality of reflective objects.

1.  The lights are creating a dark shadow below the rotation platform. This is making simple color based segmentation algorithms complex. 
I think this problem can be improved by adding a larger diameter green paper or cloth and bend it similar to a frustum. This will cause the source to  project less shadow in the bottom without constraining the rotation.

**Comment by minhnh** [comment]
* An initial version using [OpenCV background subtraction](https://docs.opencv.org/master/d1/dc5/tutorial_background_subtraction.html) is added in b-it-bots/dataset_interface#1
* usage documentation is available under: [`docs/image_augmentation.md`](https://github.com/b-it-bots/dataset_interface/blob/master/docs/image_augmentation.md)
* future improvements for the scripts can be addressed in this repository
