### ISSUE TITLE
create train script for object detection

### ISSUE THREAD

**Issue by minhnh** [b-it-bots/mas_perception#34]
* possibly use a [common interface for dataset](https://github.com/minhnh/dataset_interface) and the `ImageDetector` abstraction to make it easier in the future to switch models
* in response to the discussion in b-it-bots/mas_domestic_robotics#104

**Comment by argenos** [comment]
Has this been pushed somewhere?

**Comment by minhnh** [comment]
since I'm hoping to keep the training ROS independent, the train script we used will most likely be pushed to [`minhnh/dataset_interface`](https://github.com/minhnh/dataset_interface), and eventually to the [`b-it-bots` fork](https://github.com/b-it-bots/dataset_interface)

**Comment by argenos** [comment]
@minhnh can you migrate this to the right repo and close this issue?

**Comment by minhnh** [comment]
We are now using the default train script in `tensorflow/models` so I'll close this one.
