### ISSUE TITLE
Incompatible with mas_domestic's kinetic branch

### ISSUE THREAD

**Issue by argenos** [b-it-bots/mas_perception#37]
This makes the scripts in `dev-env` fail, and needs some (minor) manual configuration, i.e. changing to the `devel` branch in `mas_domestic`. 

My proposed solution is to create a tag with the last version that is compatible with kinetic, and update it in [dev-env](https://github.com/b-it-bots/dev-env), since I don't think we are merging `devel`into `kinetic` in `mas_domestic` any time soon.

**Comment by minhnh** [comment]
You mean failing in Travis builds or locally? I can try to run the `dev-env`. Could you list the steps to reproduce the failures? Maybe there's a fix that can be done easily.

**Comment by argenos** [comment]
Travis doesn’t fail, but it won’t build locally.
