### ISSUE TITLE
Dependencies to mcr_algorithms

### ISSUE THREAD

**Issue by argenos** [b-it-bots/mas_perception#39]
Hi guys, 

Could you tell me why is `mcr_algorithms` in `mas_common`? What do we have there that is not being exclusively used in `mas_perception`? I've noticed at least two packages that use this: 
* `mcr_leg_detection`
* `mcr_scene_segmentation`:
   - "mcr_algorithms/wrapper/pcl_wrapper.hpp"
   - "mcr_algorithms/statistics/means.hpp"

There are quite a few packages there that are point-cloud-related. Does it make sense to move all of `mcr_algorithms` to `mas_perception`?

**Comment by minhnh** [comment]
Here are the references to `mcr_algorithms` in `mas_perception`

```sh
mcr_people_tracking/CMakeLists.txt:8:    mcr_algorithms
...
mcr_people_tracking/ros/src/waist_tracking_node.cpp:35:#include <mcr_algorithms/wrapper/pcl_wrapper.hpp>
...
mcr_people_tracking/package.xml:17:  <build_depend>mcr_algorithms</build_depend>
...
mcr_scene_segmentation/CMakeLists.txt:21:    mcr_algorithms
mcr_scene_segmentation/common/include/mcr_scene_segmentation/pointcloud_segmentation.hpp:13:#include "mcr_algorithms/wrapper/pcl_wrapper.hpp"
...
mcr_scene_segmentation/package.xml:22:  <build_depend>mcr_algorithms</build_depend>
mcr_nearest_object_detection/CMakeLists.txt:9:    mcr_algorithms
...
mcr_nearest_object_detection/ros/src/nearest_object_detection_node.cpp:23:#include <mcr_algorithms/geometry/conversions.h>
...
mcr_nearest_object_detection/package.xml:18:  <build_depend>mcr_algorithms</build_depend>
...
mcr_leg_detection/CMakeLists.txt:15:    mcr_algorithms
...
mcr_leg_detection/ros/src/leg_detection_node.cpp:52:#include <mcr_algorithms/geometry/conversions.h>
mcr_leg_detection/package.xml:22:  <build_depend>mcr_algorithms</build_depend>
...
```

Are there anything that's being used actively among these? It may make sense to use libraries instead of maintaining this package.

**Comment by mhwasil** [comment]
In mcr_scene_segmentation/.../pointcloud_segmentation.hpp, we never use this code since last year. We already merge pcl segmentation into common/src/scene_segmentation.cpp. So, yeah, I agree with @minhnh , it's better to maintain the libraries.
