### ISSUE TITLE
Refactoring of existing packages

### ISSUE THREAD

**Issue by argenos** [b-it-bots/mas_perception#4]
Migrating from  https://github.com/b-it-bots/mas_common_robotics/issues/4

We need to reorganize `mcr_perception`. We have several packages that are either for detection or recognition that would be easily grouped into fewer packages. For example:
* `mcr_object_recognition_bounding_box` and `mcr_object_recognition_mean_circle`, should be `mcr_object_recognition` with two or more nodes, i.e. `bounding_box`  and `mean_circle`?

Some of this was already addressed in #2, but some of the guilty packages are still here (see my example above).

**Comment by minhnh** [comment]
it's also important to add README to all packages as needed and remove packages in case they're not in use. This can potentially be a good task for new members.
